[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"